"""apoio

Revision ID: 196dfb340a3e
Revises: d064a854b2d1
Create Date: 2026-10-06 07:57:54.562639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196dfb340a3e'
down_revision: Union[str, Sequence[str], None] = 'd064a854b2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_apoio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ligado', sa.Boolean(), nullable=False),
    sa.Column('recebedor', sa.String(length=200), nullable=True),
    sa.Column('mensagem', sa.String(length=500), nullable=True),
    sa.Column('valores_centavos', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('compra_no_app', sa.Boolean(), nullable=False),
    sa.Column('chave_pix', sa.String(length=77), nullable=True),
    sa.Column('link_externo', sa.Text(), nullable=True),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='linha_unica'),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_apoio')
    # ### end Alembic commands ###
