"""revisao ia

Revision ID: 1bd07e0d31c6
Revises: c2d6bddb5315
Create Date: 2026-10-06 22:44:13.451602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd07e0d31c6'
down_revision: Union[str, Sequence[str], None] = 'c2d6bddb5315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisao_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('relatorio', sa.Text(), nullable=False),
    sa.Column('bloqueios', sa.Integer(), nullable=False),
    sa.Column('atencoes', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisao_ia_capitulo_id'), 'revisao_ia', ['capitulo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisao_ia_capitulo_id'), table_name='revisao_ia')
    op.drop_table('revisao_ia')
    # ### end Alembic commands ###
