"""usuarios sessoes e auditoria do admin

Revision ID: 218c12d24574
Revises: d190d5527102
Create Date: 2026-10-05 20:29:16.660530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218c12d24574'
down_revision: Union[str, Sequence[str], None] = 'd190d5527102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.Enum('administrador', 'revisor_texto', 'revisor_audio', name='papelusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('registro_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=40), nullable=True),
    sa.Column('alvo_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_auditoria_acao'), 'registro_auditoria', ['acao'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_criado_em'), 'registro_auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_usuario_id'), 'registro_auditoria', ['usuario_id'], unique=False)
    op.create_table('sessao_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessao_admin_usuario_id'), 'sessao_admin', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessao_admin_usuario_id'), table_name='sessao_admin')
    op.drop_table('sessao_admin')
    op.drop_index(op.f('ix_registro_auditoria_usuario_id'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_criado_em'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_acao'), table_name='registro_auditoria')
    op.drop_table('registro_auditoria')
    op.drop_table('usuario')
    # ### end Alembic commands ###
    # drop_table não remove o tipo enum; sem isto o upgrade seguinte falha com
    # "type papelusuario already exists".
    sa.Enum(name='papelusuario').drop(op.get_bind(), checkfirst=True)
