"""campanhas

Revision ID: 3566d40a6ae7
Revises: ef840e26776f
Create Date: 2026-10-06 13:47:40.849205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3566d40a6ae7'
down_revision: Union[str, Sequence[str], None] = 'ef840e26776f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('chave_pix', sa.String(length=77), nullable=True),
    sa.Column('pagina_doacao', sa.Text(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('meta_centavos', sa.BigInteger(), nullable=True),
    sa.Column('imagem_url', sa.Text(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrecadado_centavos', sa.BigInteger(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fim >= inicio', name='fim_depois_do_inicio'),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campanha')
    op.drop_table('instituicao')
    # ### end Alembic commands ###
