"""fila de jobs de audio

Revision ID: 43aef95cc136
Revises: 218c12d24574
Create Date: 2026-10-05 21:41:14.875659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aef95cc136'
down_revision: Union[str, Sequence[str], None] = '218c12d24574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('motor', sa.String(length=40), nullable=False),
    sa.Column('voz_narrador_id', sa.Integer(), nullable=False),
    sa.Column('voz_pergunta_id', sa.Integer(), nullable=True),
    sa.Column('voz_resposta_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendente', 'executando', 'concluido', 'falhou', name='estadojob'), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('max_tentativas', sa.Integer(), nullable=False),
    sa.Column('disponivel_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('caracteres', sa.Integer(), nullable=True),
    sa.Column('faixa_id', sa.Integer(), nullable=True),
    sa.Column('solicitado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulo.id'], ),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixa_audio.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['voz_narrador_id'], ['voz.id'], ),
    sa.ForeignKeyConstraint(['voz_pergunta_id'], ['voz.id'], ),
    sa.ForeignKeyConstraint(['voz_resposta_id'], ['voz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_audio_capitulo_id'), 'job_audio', ['capitulo_id'], unique=False)
    op.create_index('ix_job_audio_fila', 'job_audio', ['estado', 'disponivel_em'], unique=False)
    op.create_index('uq_job_audio_ativo_por_capitulo', 'job_audio', ['capitulo_id'], unique=True, postgresql_where="estado IN ('pendente', 'executando')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_job_audio_ativo_por_capitulo', table_name='job_audio', postgresql_where="estado IN ('pendente', 'executando')")
    op.drop_index('ix_job_audio_fila', table_name='job_audio')
    op.drop_index(op.f('ix_job_audio_capitulo_id'), table_name='job_audio')
    op.drop_table('job_audio')
    sa.Enum(name='estadojob').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
