"""modelo inicial

Revision ID: 60e5d5e22275
Revises: 
Create Date: 2026-10-05 12:36:40.297114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e5d5e22275'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscricao_lista_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('origem', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False),
    sa.Column('titulo_original', sa.String(length=300), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('idioma_original', sa.String(length=35), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pronuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=35), nullable=False),
    sa.Column('termo', sa.String(length=120), nullable=False),
    sa.Column('substituicao', sa.String(length=200), nullable=True),
    sa.Column('ipa', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idioma', 'termo')
    )
    op.create_table('voz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=35), nullable=False),
    sa.Column('motor', sa.String(length=40), nullable=False),
    sa.Column('voz_id', sa.String(length=120), nullable=False),
    sa.Column('papel', sa.Enum('narrador', 'pergunta', 'resposta', name='papelvoz'), nullable=False),
    sa.Column('publico', sa.Enum('adulto', 'juvenil', 'infantil', name='publico'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=35), nullable=False),
    sa.Column('publico', sa.Enum('adulto', 'juvenil', 'infantil', name='publico'), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('tradutor', sa.String(length=200), nullable=True),
    sa.Column('fonte', sa.Text(), nullable=False),
    sa.Column('notas_rodape', sa.String(length=20), nullable=False),
    sa.Column('publicada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capitulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('referencia_canonica', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.Enum('importado', 'texto_revisado', 'audio_gerado', 'audio_revisado', 'publicado', name='estadocapitulo'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edicao_id', 'ordem')
    )
    op.create_table('direitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'recusado', name='statusdireitos'), nullable=False),
    sa.Column('falecimento_tradutor', sa.Date(), nullable=True),
    sa.Column('base_legal', sa.Text(), nullable=True),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('aprovado_por', sa.String(length=200), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edicao_id')
    )
    op.create_table('faixa_audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('voz_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('duracao_ms', sa.Integer(), nullable=False),
    sa.Column('marcacoes', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulo.id'], ),
    sa.ForeignKeyConstraint(['voz_id'], ['voz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capitulo_id', 'voz_id', 'versao')
    )
    op.create_table('segmento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('titulo', 'paragrafo', 'pergunta', 'resposta', 'comentario', 'nota', name='tiposegmento'), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('numero_questao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capitulo_id', 'ordem')
    )
    op.create_index(op.f('ix_segmento_numero_questao'), 'segmento', ['numero_questao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segmento_numero_questao'), table_name='segmento')
    op.drop_table('segmento')
    op.drop_table('faixa_audio')
    op.drop_table('direitos')
    op.drop_table('capitulo')
    op.drop_table('edicao')
    op.drop_table('voz')
    op.drop_table('pronuncia')
    op.drop_table('obra')
    op.drop_table('inscricao_lista_espera')
    for nome in ('tiposegmento', 'estadocapitulo', 'statusdireitos', 'papelvoz', 'publico'):
        sa.Enum(name=nome).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
