"""conta de quem le

Revision ID: 628c86ee402d
Revises: 1bd07e0d31c6
Create Date: 2026-10-07 05:07:14.935194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628c86ee402d'
down_revision: Union[str, Sequence[str], None] = '1bd07e0d31c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigo_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('sal', sa.String(length=32), nullable=False),
    sa.Column('tentativas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigo_acesso_email'), 'codigo_acesso', ['email'], unique=False)
    op.create_table('conta_leitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acesso_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessao_conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta_leitor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessao_conta_conta_id'), 'sessao_conta', ['conta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessao_conta_conta_id'), table_name='sessao_conta')
    op.drop_table('sessao_conta')
    op.drop_table('conta_leitor')
    op.drop_index(op.f('ix_codigo_acesso_email'), table_name='codigo_acesso')
    op.drop_table('codigo_acesso')
    # ### end Alembic commands ###
