"""dispositivos e entrega de chave

Revision ID: 8944d279cf5b
Revises: 3566d40a6ae7
Create Date: 2026-10-06 18:39:52.819046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8944d279cf5b'
down_revision: Union[str, Sequence[str], None] = '3566d40a6ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desafio_atestacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('valor')
    )
    op.create_table('dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=10), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('identificador', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_uso_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('entrega_chave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('faixa_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixa_audio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entrega_chave_dispositivo_criado', 'entrega_chave', ['dispositivo_id', 'criado_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entrega_chave_dispositivo_criado', table_name='entrega_chave')
    op.drop_table('entrega_chave')
    op.drop_table('dispositivo')
    op.drop_table('desafio_atestacao')
    # ### end Alembic commands ###
