"""faixa cifrada formato e chave

Revision ID: af91f417829a
Revises: 196dfb340a3e
Create Date: 2026-10-06 07:58:22.496368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af91f417829a'
down_revision: Union[str, Sequence[str], None] = '196dfb340a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faixa_audio', sa.Column('formato', sa.String(length=10), server_default='m4a', nullable=False))
    op.add_column('faixa_audio', sa.Column('chave_cifrada', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faixa_audio', 'chave_cifrada')
    op.drop_column('faixa_audio', 'formato')
    # ### end Alembic commands ###
