"""exportacao aberta pela conta

Revision ID: c0c1b980d5f9
Revises: 628c86ee402d
Create Date: 2026-10-07 06:01:01.059726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c1b980d5f9'
down_revision: Union[str, Sequence[str], None] = '628c86ee402d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exportacao_liberada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('pedido', sa.String(length=40), nullable=False),
    sa.Column('liberada_por_id', sa.Integer(), nullable=True),
    sa.Column('liberada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revogada_por_id', sa.Integer(), nullable=True),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta_leitor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liberada_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['revogada_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exportacao_liberada_conta_id'), 'exportacao_liberada', ['conta_id'], unique=False)
    op.create_index('uq_exportacao_liberada_vigente', 'exportacao_liberada', ['conta_id'], unique=True, postgresql_where='revogada_em IS NULL')
    op.create_table('download_aberto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liberacao_id', sa.Integer(), nullable=False),
    sa.Column('faixa_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixa_audio.id'], ),
    sa.ForeignKeyConstraint(['liberacao_id'], ['exportacao_liberada.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_download_aberto_liberacao_criado', 'download_aberto', ['liberacao_id', 'criado_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_download_aberto_liberacao_criado', table_name='download_aberto')
    op.drop_table('download_aberto')
    op.drop_index('uq_exportacao_liberada_vigente', table_name='exportacao_liberada', postgresql_where='revogada_em IS NULL')
    op.drop_index(op.f('ix_exportacao_liberada_conta_id'), table_name='exportacao_liberada')
    op.drop_table('exportacao_liberada')
    # ### end Alembic commands ###
