"""temas

Revision ID: cd538a839030
Revises: defa6f51779c
Create Date: 2026-10-06 06:01:25.466435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd538a839030'
down_revision: Union[str, Sequence[str], None] = 'defa6f51779c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('idioma', sa.String(length=35), nullable=False),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tema_referencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tema_id', 'referencia')
    )
    op.create_index(op.f('ix_tema_referencia_referencia'), 'tema_referencia', ['referencia'], unique=False)
    op.create_index(op.f('ix_tema_referencia_tema_id'), 'tema_referencia', ['tema_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tema_referencia_tema_id'), table_name='tema_referencia')
    op.drop_index(op.f('ix_tema_referencia_referencia'), table_name='tema_referencia')
    op.drop_table('tema_referencia')
    op.drop_table('tema')
    # ### end Alembic commands ###
