"""blog

Revision ID: d064a854b2d1
Revises: cd538a839030
Create Date: 2026-10-06 07:33:20.376399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd064a854b2d1'
down_revision: Union[str, Sequence[str], None] = 'cd538a839030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('resumo', sa.String(length=300), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('linha', sa.Enum('kardec_responde', 'estudo_guiado', 'vida_pratica', 'pais_e_evangelizadores', 'bastidores', 'campanhas', 'novidades', name='linhaeditorial'), nullable=False),
    sa.Column('capa_url', sa.Text(), nullable=True),
    sa.Column('idioma', sa.String(length=35), nullable=False),
    sa.Column('estado', sa.Enum('rascunho', 'revisado', 'publicado', name='estadopost'), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('revisado_por_id', sa.Integer(), nullable=True),
    sa.Column('revisado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('post_referencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'referencia')
    )
    op.create_index(op.f('ix_post_referencia_post_id'), 'post_referencia', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_referencia_post_id'), table_name='post_referencia')
    op.drop_table('post_referencia')
    op.drop_table('post')
    # ### end Alembic commands ###
    # drop_table não remove os tipos enum; sem isto o upgrade seguinte falha.
    sa.Enum(name='estadopost').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='linhaeditorial').drop(op.get_bind(), checkfirst=True)
