"""subquestao no segmento

Revision ID: d190d5527102
Revises: 60e5d5e22275
Create Date: 2026-10-05 17:37:28.566922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd190d5527102'
down_revision: Union[str, Sequence[str], None] = '60e5d5e22275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segmento', sa.Column('subquestao', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segmento', 'subquestao')
    # ### end Alembic commands ###
