"""transparencia mensal

Revision ID: defa6f51779c
Revises: 43aef95cc136
Create Date: 2026-10-05 23:37:36.329263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defa6f51779c'
down_revision: Union[str, Sequence[str], None] = '43aef95cc136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mes_transparencia',
    sa.Column('mes', sa.Date(), nullable=False),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publicado_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('extract(day from mes) = 1', name='mes_no_dia_1'),
    sa.ForeignKeyConstraint(['publicado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('mes')
    )
    op.create_table('lancamento_transparencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('custo', 'arrecadacao', name='tipolancamento'), nullable=False),
    sa.Column('item', sa.String(length=120), nullable=False),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=False),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor_centavos >= 0', name='valor_nao_negativo'),
    sa.ForeignKeyConstraint(['mes'], ['mes_transparencia.mes'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamento_transparencia_mes'), 'lancamento_transparencia', ['mes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamento_transparencia_mes'), table_name='lancamento_transparencia')
    op.drop_table('lancamento_transparencia')
    op.drop_table('mes_transparencia')
    # ### end Alembic commands ###
    # drop_table não remove o tipo enum; sem isto o upgrade seguinte falha.
    sa.Enum(name='tipolancamento').drop(op.get_bind(), checkfirst=True)
