"""glossario

Revision ID: ef840e26776f
Revises: af91f417829a
Create Date: 2026-10-06 13:06:17.263764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef840e26776f'
down_revision: Union[str, Sequence[str], None] = 'af91f417829a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('termo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('termo', sa.String(length=80), nullable=False),
    sa.Column('definicao', sa.Text(), nullable=False),
    sa.Column('idioma', sa.String(length=35), nullable=False),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idioma', 'termo'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('termo_referencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termo_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=40), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['termo_id'], ['termo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('termo_id', 'referencia')
    )
    op.create_index(op.f('ix_termo_referencia_referencia'), 'termo_referencia', ['referencia'], unique=False)
    op.create_index(op.f('ix_termo_referencia_termo_id'), 'termo_referencia', ['termo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_termo_referencia_termo_id'), table_name='termo_referencia')
    op.drop_index(op.f('ix_termo_referencia_referencia'), table_name='termo_referencia')
    op.drop_table('termo_referencia')
    op.drop_table('termo')
    # ### end Alembic commands ###
