"""seo

Revision ID: f1092e382dbc
Revises: 3566d40a6ae7
Create Date: 2026-10-06 18:39:49.682892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1092e382dbc'
down_revision: Union[str, Sequence[str], None] = '3566d40a6ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capitulo', sa.Column('seo_titulo', sa.String(length=60), nullable=True))
    op.add_column('capitulo', sa.Column('seo_descricao', sa.String(length=160), nullable=True))
    op.add_column('edicao', sa.Column('seo_titulo', sa.String(length=60), nullable=True))
    op.add_column('edicao', sa.Column('seo_descricao', sa.String(length=160), nullable=True))
    op.add_column('post', sa.Column('seo_titulo', sa.String(length=60), nullable=True))
    op.add_column('post', sa.Column('seo_descricao', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'seo_descricao')
    op.drop_column('post', 'seo_titulo')
    op.drop_column('edicao', 'seo_descricao')
    op.drop_column('edicao', 'seo_titulo')
    op.drop_column('capitulo', 'seo_descricao')
    op.drop_column('capitulo', 'seo_titulo')
    # ### end Alembic commands ###
